baseURL: https://wybeharms-portfolio.netlify.app/
languageCode: en-us
title: Wybe's portfolio
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Welcome to my portfolio website. Here you will find information about me and some
      work I have done during my Masters in Analytics at LBS!
    title: Hi, my name is Wybe Harms
  blog: {}
  contact: 
    address:
      - city: Amsterdam, 250 1076DZ
        country: The Netherlands
        street: Afroditekade
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: wybeharms@gmail.com
        title: Personal Email
      - email: wharms.mam2023@london.edu
        title: LBS Email
    enable: yes
    phone:
      - phone: (+31) 6 54686717
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [apple.com](/)
  favicon: favicon.ico
  footer:
    copyright: Wybe Harms
    enable: yes
    quicklinks:
      - alt: 
        text:
        url: 
    social:
      - icon: \#
        label: \#
        url: \#
      - icon: fa-snapchat
        label: Snapchat
        url: https://www.snapchat.com/ 
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/wybe.harms/
      - icon: fa-github
        label: GitHub
        url: https://github.com/wybeharms
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/wybe-harms-43937194/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: 
    title: 
  tiles:
    enable: yes
    showcase:
      - image: Background picture.jpg
        subtitle: Learn more about Wybe!
        title: About me
        url: blogs/about_me
        
      - image: portrait.JPG
        subtitle: Learn more about my academic and professional experiences
        title: CV
        url: blogs/Christiaan WybeHarms_Resume LBS.pdf
        
      - image: santander_bikes.jpeg
        subtitle: Regression analysis of how many bikes will be hired
        title: Santander Bikes London
        url: blogs/santander_bikes
        
      - image: bank_of_london.jpeg
        subtitle: Was there discrimination at Bank of London
        title: Bank of London
        url: blogs/bank_of_london

