---
title: "Analytics Projects"
date: "2023-02-22"
description: ''
draft: no
image: null
keywords: ''
slug: my_projects
categories:
- ''
- ''
---

## Feel free to explore some data analytics projects I have worked on during my Masters in Analytics:

### Easy

Simple data cleaning, t-test hypothesis to analyse differences in default rate between certain groups

[Bank of London](https://www.dropbox.com/s/0yjk432zcdan1te/Bank_of_London.html?raw=1)

### Medium 

Using ggplot in R to visualize three trends in Stop and Seach activity in London. Data downloaded from data.police.uk

[Stop and Search Visualizations](https://www.dropbox.com/s/xudxu55wo021bzq/problem_set_2_wybe.html?raw=1)

### Hard

Built multiple predictive models to predict the price of a given property. Compared linear regression, trees, kNN, GBD trees and stacking models

[Predicting House Prices](https://www.dropbox.com/s/3tw6k6976sldp7z/Harms_Wybe_London_house_prices_individual_workshop.html?raw=1)

Cleaning, inspecting and exploring a large data set (25 million rows) on movie ratings. Used a 2% of data to build and compare 3 collaborative filtering based recommendation models

[Recommendation Systems](https://www.dropbox.com/s/cxgsurq8uhwzucl/wybe_part1.html?raw=1)

Using the data from movie ratings, I performed text mining and PCA on the tags given for each rating 

[Text Mining](https://www.dropbox.com/s/0hw85sxcivsoegk/part2_wybe--1-.html?raw=1)

Next, I used the first 10 columns returned by the PCA calculated before to train and test an SVM model to classify ratings as being excellent or not

[Support Vector Machines](https://www.dropbox.com/s/5uwfdr8iz67pw0u/part3_A_wybe.html?raw=1)

Lastly, the PCA data was used as an input to an Artificial Neural Network (ANN)

[Artificial Neural Network](https://www.dropbox.com/s/b82egekmxmmxafw/part3_B.html?raw=1)


